### ISSUE TITLE
FIX for Jboss java.lang.NoClassDefFoundError: org/jboss/modules/ModuleLoader

### ISSUE THREAD

**Issue by chris-str-cst** [mp911de/logstash-gelf#156]
I got the following error after I completed your instructions [.](http://logging.paluch.biz/examples/jbossas7.html) Version 1.11.x and 1.12

```bash 2018-10-01 12:13:02,724 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([


    ("subsystem" => "logging"),
    ("custom-handler" => "GelfLogger")

]): java.lang.IllegalArgumentException: Failed to load module "biz.paluch.logging" for handler "GelfLogger"
at org.jboss.logmanager.config.AbstractPropertyConfiguration.<init>(AbstractPropertyConfiguration.java:64)
	at org.jboss.logmanager.config.HandlerConfigurationImpl.<init>(HandlerConfigurationImpl.java:51)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.addHandlerConfiguration(LogContextConfigurationImpl.java:142)
	at org.jboss.as.logging.logmanager.ConfigurationPersistence.addHandlerConfiguration(ConfigurationPersistence.java:190)
	at org.jboss.as.logging.HandlerOperations$HandlerAddOperationStepHandler.createHandlerConfiguration(HandlerOperations.java:311)
	at org.jboss.as.logging.HandlerOperations$HandlerAddOperationStepHandler.performRuntime(HandlerOperations.java:229)
	at org.jboss.as.logging.LoggingOperations$LoggingAddOperationStepHandler$1.execute(LoggingOperations.java:204)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890) 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659) at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1349)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:495)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:389)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:351)
	at org.jboss.as.server.ServerService.boot(ServerService.java:402)
	at org.jboss.as.server.ServerService.boot(ServerService.java:371)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:301)
	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NoClassDefFoundError: org/jboss/modules/ModuleLoader

	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ModuleFinder.getClassLoader(AbstractPropertyConfiguration.java:463)

	at org.jboss.logmanager.config.AbstractPropertyConfiguration.<init>(AbstractPropertyConfiguration.java:62)
	... 17 more```


I needed to add export JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_HOME/jboss-modules.jar" to the java opts make it work. Maybe this is helpful for some. My JBoss-eap 7.0.9 is running in standalone-full-HA.xml

**Comment by mp911de** [comment]
What WildFly (JBoss) version did you use? Can you provide your logging configuration as it's not possible to diagnose the issue without additional context.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
