### ISSUE TITLE
UDP connections throw exception even though it seems they should fire and forget

### ISSUE THREAD

**Issue by ursine** [mp911de/logstash-gelf#210]
I'm using the UDP transport to send logs to Graylog... when Graylog is running, everything works as expected.  If Graylog is not available I get the following exception thrown (graylog is running on docker at localhost:12200, UDP transport).

Is this a bug, or user error, or expected behavior?

```
12:24:59.449 [main] INFO  c.t.l.i.UrlJsonIncidentReader - Opening the URL and starting to stream
12:24:59,465 |-ERROR in biz.paluch.logging.gelf.logback.GelfLogbackAppender[gelf] - Port localhost:12200 not reachable java.net.PortUnreachableException
	at java.net.PortUnreachableException
	at 	at java.base/sun.nio.ch.DatagramDispatcher.read0(Native Method)
	at 	at java.base/sun.nio.ch.DatagramDispatcher.read(DatagramDispatcher.java:43)
	at 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at 	at java.base/sun.nio.ch.DatagramChannelImpl.read(DatagramChannelImpl.java:607)
	at 	at biz.paluch.logging.gelf.intern.sender.AbstractNioSender.isConnected(AbstractNioSender.java:77)
	at 	at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendDatagrams(GelfUDPSender.java:54)
	at 	at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.sendMessage(GelfUDPSender.java:47)
	at 	at biz.paluch.logging.gelf.logback.GelfLogbackAppender.append(GelfLogbackAppender.java:92)
	at 	at biz.paluch.logging.gelf.logback.GelfLogbackAppender.append(GelfLogbackAppender.java:65)
	at 	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at 	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at 	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at 	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at 	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at 	at ch.qos.logback.classic.Logger.info(Logger.java:583)

```

**Comment by mp911de** [comment]
UDP transport isn't ignoring I/O exceptions. If the sender receives an ICMP destination unreachable packet, then `PortUnreachableException` is thrown. UDP does not require receive confirmation as in TCP ACK, therefore you trade performance for reliability.

**Comment by ursine** [comment]
Makes complete sense.  Thanks!  I was thinking UDP was more "spray-and-pray" than it turns out to be -- conflating delivery confirmation and the opening of the port.
