### ISSUE TITLE
Can't load log handler 

### ISSUE THREAD

**Issue by jakubwlodarczyk94** [mp911de/logstash-gelf#234]
Hello everyone,

I would like to set this plugin inside of container Jenkins on java 11.
It was working on Jenkins on Java 8, but after change it to Java 11 I got this message:

<pre><code>
Can't load log handler "biz.paluch.logging.gelf.jul.GelfLogHandler"
java.lang.ClassNotFoundException: biz.paluch.logging.gelf.jul.GelfLogHandler
java.lang.ClassNotFoundException: biz.paluch.logging.gelf.jul.GelfLogHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.logging/java.util.logging.LogManager.createLoggerHandlers(LogManager.java:1000)
	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:970)
	at java.logging/java.util.logging.LogManager$4.run(LogManager.java:966)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.logging/java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:966)
	at java.logging/java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:2417)
	at java.logging/java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:2511)
	at java.logging/java.util.logging.Logger.getHandlers(Logger.java:2089)
	at winstone.Launcher.main(Launcher.java:335)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Main._main(Main.java:375)
	at Main.main(Main.java:151)
</code></pre>

I builded the newest version on environment jdk-11 but it doesn't help.

Any  idea? 

Best regards,

**Comment by mp911de** [comment]
Likely you need to add the appender and it’s dependencies to the boot classloader as JUL logging uses that one instead of the application class loader.

**Comment by jakubwlodarczyk94** [comment]
In the file: _/etc/java-11-openjdk/logging.properties_ my appenders looks like:

handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler, biz.paluch.logging.gelf.jul.GelfLogHandler

Should I change it to another one, or remove it at all?

**Comment by mp911de** [comment]
This choice depends on how you intend to configure your application. We cannot help with that kind of questions.

Closing this ticket as the original issue isn't related to logstash-gelf.
